# Generated by Django 5.2.5 on 2025-08-29 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('address1', models.CharField(blank=True, default='', max_length=255)),
                ('address2', models.CharField(blank=True, default='', max_length=255)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('country', models.CharField(default='SE', max_length=2)),
                ('billing_same_as_shipping', models.BooleanField(default=True)),
                ('billing_address1', models.CharField(blank=True, default='', max_length=255)),
                ('billing_address2', models.CharField(blank=True, default='', max_length=255)),
                ('billing_postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('billing_city', models.CharField(blank=True, default='', max_length=80)),
                ('billing_country', models.CharField(blank=True, default='', max_length=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
