# Generated by Django 5.2.5 on 2025-09-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
