# Generated by Django 3.2.25 on 2025-08-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("hex", models.CharField(blank=True, max_length=7, null=True)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("category", models.CharField(max_length=50)),
                ("image_catalog", models.ImageField(blank=True, null=True, upload_to="catalog/")),
                ("image_details", models.ImageField(blank=True, null=True, upload_to="details/")),
            ],
        ),
    ]
